<!DOCTYPE html><?php /* @var $this \NsCore\View */ ?>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="noindex" />
        <title><?= $this->title; ?></title>  
        <base href="<?= SITE_URL ?>">
        <link rel="shortcut icon" href="favicon.ico">
        <link rel="stylesheet" href="views/_theme/css/_variables.css">
        <link rel="stylesheet" href="views/_theme/css/_grid.css">
        <link rel="stylesheet" href="views/_theme/css/form.css">
        <link rel="stylesheet" href="views/_theme/css/table.css">
        <link rel="stylesheet" href="views/_theme/css/fontello.css">
        <link rel="stylesheet" href="views/_theme/css/style.css"> 
        <script src="views/_theme/js/jquery-3.5.1.min.js"></script>
    </head>
    <body>        
        <div class="login">
            <h2 style="text-align: center">Sistema de control de acceso</h2>
            <h3 style="text-align: center">Trabaja Perú - Talavera</h3>
            <div>                
                <form method="post">
                    <?php if (\Input::exist('logout', 'get')): ?>
                        <div class="alert-success">Has cerrado sesión.</div>
                    <?php elseif (\Input::exist('require', 'get')): ?>
                        <div class="alert-danger">Nesecita iniciar sesión para realizar esta operación.</div>
                    <?php endif; ?>
                    <input type="hidden" value="<?= \Input::get_token('account-login') ?>" name="_token">
                    <div class="form-group">
                        <h1>Iniciar Sesión</h1>
                    </div>                    
                    <div class="input-group">
                        <label class="input-group-prepend" for="user_email"><i class="icon-mail"></i></label>
                        <input type="email" required name="user_email" id="user_email" placeholder="Correo electrónico" value="<?= \Input::value('user_email') ?>"
                               class="form-control <?= \Input::was_invalid('user_email') ? 'is-invalid' : (\Input::was_valid('user_email') ? 'is-valid' : '') ?>">

                        <?php if (\Input::was_invalid('user_email')): ?>
                            <div class="invalid-feedback">
                                <?= \Input::get_error('user_email') ?>
                            </div>
                        <?php endif; ?>
                        <?php if (\Input::was_valid('user_email')): ?>
                            <div class="valid-feedback">Se ve bien</div>
                        <?php endif; ?>
                    </div>
                    <div class="input-group">
                        <label class="input-group-prepend" for="user_pass"><i class="icon-key"></i></label>
                        <input type="password" class="form-control <?= \Input::was_invalid('user_pass') ? 'is-invalid' : (\Input::was_valid('user_pass') ? 'is-valid' : '') ?>" 
                               required name="user_pass" id="user_pass" placeholder="Contraseña" value="<?= \Input::value('user_pass') ?>">
                        <div class="input-group-append"><i class="icon-eye-off"></i></div>
                        <?php if (\Input::was_invalid('user_pass')): ?>
                            <div class="invalid-feedback"><?= \Input::get_error('user_pass') ?></div>
                        <?php endif; ?>
                        <?php if (\Input::was_valid('user_pass')): ?>
                            <div class="valid-feedback">Se ve bien</div>
                        <?php endif; ?>
                    </div>
                    <?php if (\Input::error_exist()): ?>
                        <div class="alert-danger">
                            <div><?= implode('</div><div>', \Input::get_form_errors()) ?></div>
                        </div>
                    <?php endif; ?>
                    <button class="btn btn-primary" type="submit">Acceder</button>
                </form>
                <script>
                    $('.input-group').on('click', '.input-group-append', function () {
                        var _i = $(this).children('i');
                        if (_i.attr('class') == 'icon-eye') {
                            _i.removeClass('icon-eye').addClass('icon-eye-off');
                            $(this).siblings('input').attr('type', 'password');
                        } else if (_i.attr('class') == 'icon-eye-off') {
                            _i.removeClass('icon-eye-off').addClass('icon-eye');
                            $(this).siblings('input').attr('type', 'text');
                        }
                    });
                </script>
                <p class="recuperar-cuenta"><i class="icon-help-circled"></i><a href="#">Olvidé mi contraseña.</a></p>
            </div>   
            <footer>
                <p>Copyright © <a href="#" target="_blank">2021</a> - Edison Ataucusi Romero</p>      
            </footer>
        </div> 
    </body>
</html>