<?php /* @var $this \NsCore\View */ ?>
<div class="container"> 
    <h2>Mi contraseña</h2>
    <p><a href="account/info">Cambiar mis datos</a></p>
    <form method="post"  autocomplete="off" class="scorm-add">
        <?php if (\Session::exist('message')): ?>
            <div class="alert-success"><?= \Session::get_remove('message') ?></div>
        <?php endif; ?>
        <input type="hidden" name="_token" value="<?= \Input::get_token('account-password') ?>">        
        <div class="input-group">
            <label for="user_pass" class="input-group-prepend">Contraseña actual</label>
            <input type="password" class="form-control <?= \Input::was_invalid('user_pass') ? 'is-invalid' : '' ?>" name="user_pass" id="user_pass" required value="<?= \Input::value('user_pass') ?>">
            <button type="button" class="btn btn-warning input-group-append"><i class="icon-eye-off"></i></button>
            <?php if (\Input::was_invalid('user_pass')): ?>
                <div class="invalid-feedback">
                    <?= \Input::get_error('user_pass') ?>
                </div>
            <?php endif; ?>
        </div> 
        <div class="input-group">
            <label for="new_pass" class="input-group-prepend">Nueva contraseña</label>
            <input type="password" class="form-control <?= \Input::was_invalid('new_pass') ? 'is-invalid' : '' ?>" name="new_pass" id="new_pass" required value="<?= \Input::value('new_pass') ?>">
            <button type="button" class="btn btn-warning input-group-append"><i class="icon-eye-off"></i></button>
            <?php if (\Input::was_invalid('new_pass')): ?>
                <div class="invalid-feedback">
                    <?= \Input::get_error('new_pass') ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="input-group">
            <label for="re_pass" class="input-group-prepend">Nueva contraseña</label>
            <input type="password" class="form-control <?= \Input::was_invalid('re_pass') ? 'is-invalid' : '' ?>" name="re_pass" id="re_pass" required value="<?= \Input::value('re_pass') ?>">
            <button type="button" class="btn btn-warning input-group-append"><i class="icon-eye-off"></i></button>
            <?php if (\Input::was_invalid('re_pass')): ?>
                <div class="invalid-feedback">
                    <?= \Input::get_error('re_pass') ?>
                </div>
            <?php endif; ?>
        </div>
        <?php if (\Input::error_exist()): ?>
            <div class="alert-danger">
                <div><?= implode('</div><div>', \Input::get_form_errors()) ?></div>
            </div>
        <?php endif; ?>
        <button type="submit" class="btn btn-success"><i class="icon-floppy"></i> Guardar</button>
    </form>
</div>
<script>
    $('.input-group').on('click', 'button.input-group-append', function () {
        var _i = $(this).children('i');
        if (_i.attr('class') == 'icon-eye') {
            _i.removeClass('icon-eye').addClass('icon-eye-off');
            $(this).siblings('input').attr('type', 'password');
        } else if(_i.attr('class') == 'icon-eye-off') {
            _i.removeClass('icon-eye-off').addClass('icon-eye');
            $(this).siblings('input').attr('type', 'text');
        }
    });
</script>