<!DOCTYPE html><?php /* @var $this \NsCore\View */ ?>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="noindex"/>
        <title><?= $this->title ?></title>  
        <base href="<?= SITE_URL ?>">
        <link rel="shortcut icon" href="favicon.ico">
        <link rel="stylesheet" href="views/_theme/css/_grid.css">
        <link rel="stylesheet" href="views/_theme/css/_variables.css">
        <link rel="stylesheet" href="views/_theme/css/form.css">
        <link rel="stylesheet" href="views/_theme/css/table.css">  
        <link rel="stylesheet" href="views/_theme/css/fontello.css">
        <link rel="stylesheet" href="views/_theme/css/style.css"> 
        <?php $length = count($this->css) ?>
        <?php for ($i = 0; $i < $length; $i++): ?>
            <link rel="stylesheet" href="<?= $this->css[$i]; ?>">
        <?php endfor; ?>
        <script src="views/_theme/js/jquery-3.5.1.min.js"></script>
        <?php $length = count($this->js_head) ?>
        <?php for ($i = 0; $i < $length; $i++): ?>
            <script src="<?= $this->js_head[$i]; ?>"></script>
        <?php endfor; ?>
    </head>
    <body>
        <header class="container-fluid">
            <h1>
                <a href="<?= SITE_URL ?>">Control de acceso</a>
            </h1>                   
            <ul>
                <li><a href="main/report">Reportes</a></li>
                <li><a href="main/syncs">Sincronización</a></li>
                <li class="account"><a href="account/info" title="Mis datos"><i class="icon-user"></i><?= \Session::get('user_login') ?></a><a href="account/logout" title="Salir"><i class="icon-cancel-circled"></i></a></li>
            </ul>
        </header>
        <main>
            <div class="container-fluid">
                <?= $this->content ?>
            </div>            
        </main>
        <footer>
            <p>Copyright © <a href="#">2021</a> - Edison Ataucusi Romero.</p>      
        </footer>
        <?php $length = count($this->js_body) ?>
        <?php for ($i = 0; $i < $length; $i++): ?>
            <script src="<?= $this->js_body[$i]; ?>"></script>
        <?php endfor; ?>
    </body>
</html>